# Generated by Django 5.0.2 on 2024-04-02 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='category',
        ),
        migrations.RemoveField(
            model_name='news',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='news',
            name='view_count',
        ),
    ]
